### ISSUE TITLE
Space separated list of values for "multiple" options

### ISSUE THREAD

**Issue by patak-dev** [egoist/tinyargs#7]
For Vitest, we're looking for a way to support CLI options like https://jestjs.io/docs/cli#--findrelatedtests-spaceseparatedlistofsourcefiles, where you can pass a comma-separated list of values `--option value1 value2` instead of needing to repeat `--option value1 --option value2`. 
In both cac (currently in use) and tinyargs (maybe we can move to it), for `--option value1 value2` value2 is interpreted as a positional argument.
Is this something that you may want to support in this project? Maybe as a flag to avoid the breaking change? Or is there a hard rationale for not supporting this, that we may want to adhere to

**Comment by egoist** [comment]
I think your title should be "space separated list"? Maybe I'll add this, in the meantime I think yargs supports this already, maybe you can just use it.

**Comment by patak-dev** [comment]
Thanks for considering it and for being able to understand the issue with such a confusing title :)

**Comment by patak-dev** [comment]
After some discussions (lukeed discouraged supporting space-separated list), I don't think this is worth supporting. Closing for the moment. Thanks!
